repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: trailing-whitespace
    exclude: ^docs/
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.2.0
  hooks:
  - id: insert-license
    files: '^explabox/.*py'
    args:
      - --detect-license-in-X-top-lines=12
      - --license-filepath=.shortlicense
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: "Dependency order: isort"
    args:
      - --profile=black
      - --line-length=120
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    name: "Linter: black"
    args:
      - --line-length=120
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
  - id: bandit
    args:
      - --configfile=.bandit.yaml
- repo: https://github.com/mgedmin/check-manifest
  rev: "0.48"
  hooks:
  - id: check-manifest
- repo: local
  hooks:
  - id: build-documentation
    name: Build Documentation
    language: system
    entry: sphinx-apidoc --module-first --no-toc --force --templatedir=docs/source/_templates/ -o docs/source/api explabox
    types: [python]
